### PR TITLE
normalize input -same as `goflags.NormalizedStringSliceOptions`

### LINKED ISSUE #1071: [Issue] Capitalization in domains breaks subfinder when reading from a domain list input file
**Describe the bug**
Subfinder is literal about capitlization when reading from an input file. Capitalization in domain names causes no subdomains to be found. This only seems to occur with the `-dL` flag, not the `-d` flag.

**Subfinder version**
v.2.6.3

**Complete command you used to reproduce this**
`echo 'Google.com' >> google.txt`
`subfinder -dL google.txt`
Observe zero results.
In contrast....
`subfinder -d Google.com`
Observe valid results

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by dogancanbakir**
```console
$ cat domain.lst 
Google.com

$ go run . -dL domain.lst 

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.4-dev (development)
[INF] Loading provider config from /home/vscode/.config/subfinder/provider-config.yaml
[INF] Enumerating subdomains for google.com

...
googleproxy-66-249-83-183.google.com
mailit0-f43.google.com
sandbox.r2.sn-n4v7snlr.c.pack.google.com
mailqk0-f152.google.com
alt83.www.google.com
alt2871.www.google.com
googleproxy-66-249-88-182.google.com
mail-ads.r4.sn-vgqsrnld.c.pack.google.com
[INF] Found 13386 subdomains for google.com in 20 seconds 394 milliseconds
```

Closes #1071.

### CODE REVIEW

File: v2/pkg/runner/util.go [hunk 1]
```diff
@@ -36,3 +37,7 @@ func sanitize(data string) (string, error) {
 	}
 	return data, nil
 }
+
+func normalizeLowercase(s string) string {
```
Comment (Mzack9999) [inline v2/pkg/runner/util.go:41]: wouldn't this be equivalent to:
```go
return strings.ToLower(sanitize(s))
```

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
marking as `Request Changes` to review a minor suggested change

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
